### PR TITLE
Fix [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26

### LINKED ISSUE #574: [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
We are experiencing this warning multiple times whenever we try to rebuild caches via Drush in a custom project based on farmOS:

```
$ drush cr
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [warning] Invalid argument supplied for foreach() EntityViewsDataTaxonomyFilterTrait.php:26
 [success] Cache rebuild complete.
```

I haven't had a chance to dig in and figure out what's happening. It doesn't seem to be causing any issues.

Here is the relevant line of code producing the warning: https://github.com/farmOS/farmOS/blob/f60478f6df89b966fc89637400b8e3d92ca4d4c2/modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php#L26

### PR DESCRIPTION
**Pull request by mstenta**
Fixes https://github.com/farmOS/farmOS/issues/574

### CODE REVIEW

File: modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php [hunk 1]
```diff
@@ -22,11 +22,12 @@ protected function addReverseRelationships(array &$data, array $fields) {
...
       }
-      $table_name = $this->tableMapping->getFieldTableName($field->getName());
-      foreach ($data[$table_name] as $table_field_name => $field_data) {
-        $field_name = $field->getName();
-        if (isset($field_data['filter']) && strpos($table_field_name, $field_name) === 0) {
-          $data[$table_name][$table_field_name]['filter']['id'] = 'taxonomy_index_tid';
+      $field_name = $field->getName();
+      foreach ($data as $table_name => $table_data) {
+        foreach ($table_data as $table_field_name => $field_data) {
+          if (isset($field_data['filter']) && strpos($table_field_name, $field_name) === 0) {
```
Comment (paul121) [inline modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: > `strpos($table_field_name, $field_name) === 0`

I'm curious why we can't check that `$table_field_name == $field_name` ? I think it could be possible that two different fields have the same prefix and this logic could inadvertently change the filter ID for the wrong field.

Consider two field names: Taxonomy reference `custom_field` and String `custom_field_raw`. I think this logic would change `custom_field_raw` to use the `taxonomy_index_tid` filter.

Comment (paul121) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: but I think this approach should work! :+1:

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: > Consider two field names: Taxonomy reference `custom_field` and String `custom_field_raw`. I think this logic would change `custom_field_raw` to use the `taxonomy_index_tid` filter.

That's a good point.

I'm not sure why we used `strpos($table_field_name, $field_name) === 0` originally. Here is the commit that added it, if it rings any bells: https://github.com/farmOS/farmOS/commit/7358e4d64c97f156994ddc1f821109d78d740eaf

This PR doesn't change that bit, just restructures the `foreach` so that we don't need to figure out `$table_name`.

I wonder if there was a good reason for using `strpos`... :thinking:

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: > This PR doesn't change that bit, just restructures the `foreach` so that we don't need to figure out `$table_name`.

Ah but I see how that would introduce this issue, as we are no longer limiting which tables this logic can potentially run on...

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: Ah ok... just ran this through the debugger and quickly realized why we used `strpos()`...

Example:

- `$table_field_name` is `animal_type_target_id`
- `$field_name` is `animal_type`

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: But not for all of them...

Example:

- `$table_field_name` is `units`
- `$field_name` is `units`

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: Perhaps we could do:

`if (isset($field_data['filter']) && in_array($table_field_name, [$field_name, $field_name . '_target_id'])) {`

... basically checking if it's either `$field_name` or `$field_name . '_target_id'`.

Comment (mstenta) [reply modules/core/entity/modules/views/src/EntityViewsDataTaxonomyFilterTrait.php]: >  I think it could be possible that two different fields have the same prefix and this logic could inadvertently change the filter ID for the wrong field.

Ah ha! Sure enough I found a case where this happens in the custom codebase I'm working in, which has both `field_input` and `field_input_date` fields.

**Comment by mstenta** [comment]
OK. Force-pushed the commit to implement this change. I also restructured the code to make the logic more readable with extra comments etc.

**Review by paul121 — APPROVED** [review]
Thanks for adding the comments :-)
