### PR TITLE
Fix incorrect CSV headers when exporting multiple record types

### LINKED ISSUE #805: Export CSV on all assets/logs chooses header columns from the first asset/log in the list
When using the Export CSV button from all /assets or all /logs page, only the header columns from the first asset in the list are chosen.

From 3.1.0 release blog post... "In previous versions, only the columns that are visible on the page were included in the CSV. Now, the columns include all text, reference, timestamp, and boolean data by default."

This works fine for exporting similar asset/log types.  But not for "all" pages that include multiple types.

**Expected behavior**
- Perhaps "all" pages could only export the columns visible on the all /assets and all /logs pages.
  - assets: id, asset_type, status
  - logs: status, id, timestamp, name, log_type, owner
- Or "all" pages could specify all fields that are common to all assets/logs
  - assets: id,uuid,type,uid,name,status,created,changed,archived,notes,flag,location,is_location,is_fixed,owner,parent,quick
  - logs: id,uuid,type,uid,name,timestamp,status,created,changed,notes,flag,location,is_movement,asset,category,owner,equipment,quick
- Or "all" pages could hide the option to export from the dropdown altogether.

**Example assets export**
id,uuid,type,uid,name,status,created,changed,archived,notes,flag,location,is_location,is_fixed,owner,parent,quick,animal_type,birthdate,is_castrated,nickname,sex
2,952f0dac-a9ba-4ecb-b042-269d298a797e,animal,admin,"test animal",active,2024-03-19T20:57:35+00:00,2024-03-19T20:57:35+00:00,,,,,,,,,,"test breed",,,,
3,1cdcfa41-6f0b-4bf6-8981-7cf694a529df,equipment,admin,"test equipment",active,2024-03-19T20:58:02+00:00,2024-03-19T20:58:02+00:00,,,,,,,,,,,,
4,44e55b63-8fa4-477f-b26b-0f815946ddb3,land,admin,"test land",active,2024-03-19T20:58:20+00:00,2024-03-19T20:58:20+00:00,,,,,1,1,,,,bed
5,310948da-b398-4efe-8516-38da54bed309,structure,admin,"test structure",active,2024-03-19T20:58:38+00:00,2024-03-19T20:58:38+00:00,,,,,1,1,,,,building
1,e79d294b-2de2-4ee2-b848-482323a52a01,plant,admin,"test tomato",active,2024-03-01T23:01:54+00:00,2024-03-01T23:01:54+00:00,,,,,,,,,,tomato,
6,5d34f390-4d1d-4dcb-85ef-ab9e2fb410c6,water,admin,"test water",active,2024-03-19T20:58:50+00:00,2024-03-19T20:58:50+00:00,,,,,1,1,,,

**Example logs export**
id,uuid,type,uid,name,timestamp,status,created,changed,notes,flag,location,is_movement,asset,category,owner,equipment,quick,lot_number,purchase_date,source
6,bf552e33-40fe-44ca-9244-c48e6874e6e5,seeding,admin,"test seeding",2024-03-19T21:37:14+00:00,pending,2024-03-19T21:37:21+00:00,2024-03-19T21:37:21+00:00,,,,1,,,admin,,,,,
5,f7ed4abe-4578-4f2d-a527-f963ffa7eee1,observation,admin,"test observation",2024-03-19T21:37:02+00:00,pending,2024-03-19T21:37:08+00:00,2024-03-19T21:37:08+00:00,,,,,,,admin,,
4,21e6178b-7219-48f8-a79b-045eb3d9fea0,maintenance,admin,"test maintenance",2024-03-19T21:36:49+00:00,pending,2024-03-19T21:36:54+00:00,2024-03-19T21:36:54+00:00,,,,,,,admin,,
3,0fee77e9-0002-453b-95ef-d0cb3bf2df69,input,admin,"test input",2024-03-19T21:36:22+00:00,pending,2024-03-19T21:36:27+00:00,2024-03-19T21:36:27+00:00,,,,,,,admin,,,,,,
2,e5b9db31-a703-4d64-8406-f7e391ac48fe,harvest,admin,"test harvest",2024-03-19T21:36:08+00:00,pending,2024-03-19T21:36:13+00:00,2024-03-19T21:36:13+00:00,,,,,,,admin,,,
1,e1c82931-28d6-4bed-b060-eb58493788fd,activity,admin,"test activity",2024-03-19T21:35:45+00:00,pending,2024-03-19T21:35:54+00:00,2024-03-19T21:35:54+00:00,,,,,,,admin,,

### PR DESCRIPTION
**Pull request by mstenta**
Fixes #805

This omits bundle-specific columns from CSV exports that includes entities of multiple bundles. It adds a warning message to the user to let them know this is happening.

It also adds the ability to select which bundles are included in the export via checkboxes.

**Original description for posterity:**

~~This is a *quick and dirty* fix. It builds the list of CSV column headers by iterating over *every* row to build a combined list. So the more rows you are exporting the less performant it may be.~~

~~So it fixes a bug at the expense of a new performance consideration, which is the lesser of two evils IMO. And it buys us some time to work on a better overall fix (along with some of the other *feature* ideas we talked about in #805).~~

~~Worth noting, one of the effects of this is that the order of columns will depend on the data, so if you export two sets of data, or if you apply different sorts to your data, you may get different column orders. But all the data will be there in the proper place.~~

### CODE REVIEW

**Comment by mstenta** [comment]
I added two more commits to this.

The first checks to see if multiple bundles are being included, and if so it adds to the warning message to highlight the fact that all columns will be included and their order may vary.

Screenshot:

Screenshot from 2024-05-09 07-35-31

The second commit adds the ability to select which columns are included in the export.

Screenshots:

Screenshot 2024-05-09 at 07-35-57 Export a CSV of 2 logs Drush Site-Install

Screenshot 2024-05-09 at 07-36-06 Export a CSV of 2 logs Drush Site-Install

File: modules/core/export/modules/csv/src/Form/EntityCsvActionForm.php [hunk 1]
```diff
@@ -319,10 +355,13 @@ public function submitForm(array &$form, FormStateInterface $form_state) {
...
    * Get a list of columns to include in CSV exports.
    *
+   * @param array|null $bundles
+   *   A list of bundles to include. If omitted, all bundles will be used.
+   *
    * @return string[]
    *   An array of column names.
    */
-  protected function getIncludeColumns() {
+  protected function getIncludeColumns($bundles = NULL) {
```
Comment (paul121) [inline modules/core/export/modules/csv/src/Form/EntityCsvActionForm.php]: Add type declaration?

Comment (mstenta) [reply modules/core/export/modules/csv/src/Form/EntityCsvActionForm.php]: fixup commit: https://github.com/farmOS/farmOS/pull/842/commits/8880e068e8ad6133aa3c2c3db47e1d6e7a9e24c9

File: modules/core/csv/src/Encoder/CsvEncoder.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+   */
+  protected function extractHeaders(array $data, array $context = []) {
+    $headers = [];
+
+    // Iterate over each row and merge its headers.
+    // This differs from the parent method in that it combines headers from all
+    // rows instead of only using headers from the first row.
+    foreach ($data as $row) {
+      $headers = array_merge($headers, array_diff(array_keys($row), $headers));
+    }
```
Comment (symbioquine) [inline modules/core/csv/src/Encoder/CsvEncoder.php]: As discussed on the dev call, using a mutable structure for accumulating the header keys should be much more efficient. It turns out the solution can be simpler than I thought too since PHP conserves key ordering in associative arrays. https://www.php.net/manual/en/language.types.array.php

```suggestion
  // Iterate over each row and accumulate the unique headers.
  // This differs from the parent method in that it combines headers from all
  // rows instead of only using headers from the first row.
  // This relies on the property of PHP arrays being ordered maps
  // so the header keys will appear in the order they are first encountered
  // when iterating over all rows.
  $unique_headers = [];
  foreach ($data as $row) {
    foreach (array_keys($row) as $header) {
      if (!array_key_exists($header, $unique_headers)) {
        // The value assigned doesn't matter here
        $unique_headers[$header] = 1;
      }
    }
  }

  $headers = array_keys($unique_headers);
```

**Comment by mstenta** [comment]
Unfortunately I realized that this PR only partially fixes #805. See this comment for more detail: https://github.com/farmOS/farmOS/issues/805#issuecomment-2104914777

So I pushed a commit to this PR that omits bundle-specific columns when multiple bundles are included in an export. This is a sacrifice of (currently broken) functionality, but it doesn't seem like we have a choice.

I will update the description of this PR accordingly, for future reference.

**Review by symbioquine — APPROVED** [review]
LGTM

**Review by paul121 — APPROVED** [review]
