### PR TITLE
Automatically rotate derivative images based on EXIF Orientation

### LINKED ISSUE #939: Issues with image orientation
Automatic image rotation has been broken for a while. I dug into it a bit this morning and I want to document what I've learned here.

Background: when a picture is taken vertically with a cell phone camera, it is often saved horizontally but contains an `Orientation` EXIF attribute that tells software how it should be displayed.

Source: https://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/

> Unfortunately, there's a small caveat. Digital camera hardware just couldn't handle saving the image directly in rotated form. So rather than performing the computationally intensive task of rotating the entire image, the camera would add a small piece of data to the file, noting which orientation the image should be in. It adds this information to the [Exif data](https://www.howtogeek.com/203592/what-is-exif-data-and-how-to-remove-it/) that all photos have (which includes the model of camera you took it with, the orientation, and possibly even [the GPS location where the photo was taken](https://www.howtogeek.com/211427/how-to-see-exactly-where-a-photo-was-taken-and-keep-your-location-private/)).
> 
> In theory, then, you could open that photo with an application, it would look at the Exif tags, and then present the photo in the correct rotation to you. The image data is saved in its original, unrotated form, but the Exif tag allows applications to correct it.

farmOS includes the Drupal [EXIF Orientation](https://www.drupal.org/project/exif_orientation) module, which has logic in it to read this `Orientation` EXIF attribute and perform the necessary rotation on the image file when it is saved.

However, this is not currently working. Attached is a test image file that you can use to replicate it. Upload this to any `image` field in farmOS (running in the official farmOS Docker image) and notice that it does not get rotated.

The reason for this is very simple (and worthy of the face-palm emoji): it relies on the `exif_read_data()` function, which is provided by the `exif` PHP extension, which is not installed by default in the `drupal` Docker image that we build our image on. 🤦

Therefore, the fix is very simple: we just need to add `docker-php-ext-install exif` to our `Dockerfile`. I've tested this locally and it fixes the issue.

HOWEVER... while I was investigating this, I learned that the act of rotating the image **strips all other EXIF data from the image file!** farmOS should always strive to maintain original data, so this is bad, and we should *not* fix this rotation issue without first preventing that data loss.

The reason that the EXIF data is lost is because Drupal uses PHP's built-in GD extension by default for image operations, and the GD extension does not preserve EXIF data. Source: https://stackoverflow.com/questions/10182890/copy-an-image-and-preserve-its-exif-iptc-data-with-php-imagecreatefromjpeg

> GD doesn't deal with Exif of IPTC data at all as its beyond the scope of what GD does.

Also this comment: https://www.php.net/manual/en/book.image.php#87566

> You know, maybe this goes without saying, but I thought I would drop a note in here.  When developing code to resize images, it is best not to use GD.  When using the current GD methodologies, you are reading content from an image and manipulating it.  By then writing that content to a brand new file, you are losing the EXIF data.
> 
> For purposes when you want to retain EXIF data, it is recommended that you compile in and use the PECL Imagick extension.  It has great resizing methods built right in and the EXIF data is retained.

It seems that the recommendation is to use the [ImageMagick](https://imagemagick.org/) PHP extension instead of GD in contexts where preservation of EXIF data is important.

However, it seems that the EXIF Orientation module does not support ImageMagick. There are two relevant issues in the queue:

- https://www.drupal.org/project/exif_orientation/issues/2895434
- https://www.drupal.org/project/exif_orientation/issues/3506468

I haven't reviewed them thoroughly, because I ran into another issue: ImageMagick does not install on Debian + PHP 8.3. 🤦 

https://github.com/Imagick/imagick/issues/630

So that's where I left off...

### PR DESCRIPTION
**Pull request by mstenta**
Fixes #939

This PR adds a new "Auto-orient" image effect to the default image styles that ship with farmOS. This effect automatically rotates derivative images based on the EXIF `Orientation` attribute.

The [EXIF Orientation](https://www.drupal.org/project/exif_orientation) module is uninstalled by this PR, and a new `farm_image` module is introduced. Notably, this does not *remove* `drupal/exif_orientation` from `composer.json`, because doing so would prevent Drupal from being able to uninstall it. So we should wait until 4.x to remove it entirely.

### CODE REVIEW

**Comment by mstenta** [comment]
The `farm_image_auto_orient` image effect is loosely based on the following implementations found in contrib:

- [EXIF Orientation](https://www.drupal.org/project/exif_orientation) module: https://git.drupalcode.org/project/exif_orientation/-/blob/87e23ab0cd2b237f05d0aeda2bc23f441f54452e/exif_orientation.module#L62
- [Image Effects](https://www.drupal.org/project/image_effects) module:
  - `AutoOrientImageEffect`: https://git.drupalcode.org/project/image_effects/-/blob/730a1e6f5f947ef4d6eec5d359c6968ce93594f9/src/Plugin/ImageEffect/AutoOrientImageEffect.php
  - `AutoOrient` (ImageMagick): https://git.drupalcode.org/project/image_effects/-/blob/730a1e6f5f947ef4d6eec5d359c6968ce93594f9/src/Plugin/ImageToolkit/Operation/imagemagick/AutoOrient.php
  - `AutoOrient` (GD2): https://git.drupalcode.org/project/image_effects/-/blob/730a1e6f5f947ef4d6eec5d359c6968ce93594f9/src/Plugin/ImageToolkit/Operation/gd/AutoOrient.php
- [Imagick](https://www.drupal.org/project/imagick) module:
  - `AutorotateImageEffect`: https://git.drupalcode.org/project/imagick/-/blob/373da420d5fff9f7a8a9d5dca46846c28e3797c2/src/Plugin/ImageEffect/AutorotateImageEffect.php
  - `Autorotate`: https://git.drupalcode.org/project/imagick/-/blob/373da420d5fff9f7a8a9d5dca46846c28e3797c2/src/Plugin/ImageEffect/AutorotateImageEffect.php

All of them work very similarly, by reading the EXIF data and performing transformations based on the value.

Here is my reasoning for rolling our own image effect instead of using one of the contrib ones:

- I want to drop our `exif_orientation` dependency, because it alters the *original* image, and without ImageMagick that means that EXIF data is lost during the transformation. See #939 for a lot more detail.
- The [Image Effects](https://www.drupal.org/project/image_effects) module requires the [ImageMagick](https://www.drupal.org/project/imagemagick) module, which we will not be adding. If anything, we will add the [Imagick](https://www.drupal.org/project/imagick) module (PR: #940)
- This PR takes priority over PR #940. We need to fix image orientation issues first, regardless. So we need our own image effect.
- If we decide to merge #940, then we will be adding the [Imagick](https://www.drupal.org/project/imagick) module, which comes with its own `Autorotate` image effect that serves the same purpose. However, this only works with ImageMagick, not GD2, which means we would need to require ImageMagick, which would be a breaking change. We can consider doing that in farmOS 4.x, and at that time we can decide if we want to replace our custom image effect.

**Comment by mstenta** [comment]
Also, IMO this can be merged as a patch release because it fixes a bug (#939). #940 will need to be merged in a minor release, at the very least, if not a major release (4.x).

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+        $result = $image->apply('mirror', ['x_axis' => TRUE]);
+        if ($result) {
+          $result = $image->apply('rotate', ['degrees' => 90]);
+        }
+        break;
+
+      case 8:
+        $result = $image->apply('rotate', ['degrees' => 270]);
+        break;
+    }
```
Comment (symbioquine) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: For larger chunks of code that appear directly derived from [other code](https://git.drupalcode.org/project/image_effects/-/blob/730a1e6f5f947ef4d6eec5d359c6968ce93594f9/src/Plugin/ImageToolkit/Operation/gd/AutoOrient.php#L45-86), my understanding is that there should be some sort of inline attribution indicating where the code was copied/modified from.

We can argue about whether this code is too much of boiler-plate for the GPL attribution/copyright-listing requirements to come into play (obligatory IAANAL), but at the very least I'd argue for perma-linking to the source of the copied code since that also has come in handy to me in the past when troubleshooting errors that crept into adapted code.

File: modules/core/image/farm_image.install [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+  // Add auto-orient effect to Drupal core image styles.
+  $styles = [
+    'large',
+    'medium',
+    'thumbnail',
+    'wide',
+  ];
+  foreach ($styles as $name) {
+    $style = ImageStyle::load($name);
+    $style->addImageEffect([
```
Comment (symbioquine) [inline modules/core/image/farm_image.install]: Is there any argument for being more defensive here - i.e. if one style doesn't exist or fails to load, should it fail entirely or proceed to the others?

File: modules/core/entity/farm_entity.post_update.php [hunk 3]
```diff
@@ -24,3 +24,12 @@ function farm_entity_post_update_enforce_plan_eri(&$sandbox) {
 function farm_entity_post_update_rebuild_bundle_field_maps(&$sandbox = NULL) {
   \Drupal::service('entity_field.manager')->rebuildBundleFieldMap();
 }
+
+/**
+ * Uninstall EXIF Orientation module.
+ */
+function farm_entity_post_update_uninstall_exif_orientation() {
+  if (\Drupal::service('module_handler')->moduleExists('exif_orientation')) {
+    \Drupal::service('module_installer')->uninstall(['exif_orientation']);
```
Comment (symbioquine) [inline modules/core/entity/farm_entity.post_update.php]: What happens if somebody copied the `farm_entity.info.yml` file's dependencies into a contrib module and inadvertently (or intentionally) depends on the `exif_orientation` module? Would this force their module to be uninstalled also, or would this fail?

File: docker/Dockerfile [hunk 4]
```diff
@@ -30,8 +30,8 @@ RUN apt-get update && apt-get install -y libgeos-dev \
     && make install \
     )
 
-# Install the BCMath PHP extension.
-RUN docker-php-ext-install bcmath
+# Install the BCMath and Exif PHP extensions.
+RUN docker-php-ext-install bcmath exif
```
Comment (symbioquine) [inline docker/Dockerfile:34]: Do we need to update any of our documentation regarding farmOS' expectations about its environment?

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 5]
```diff
@@ -0,0 +1,204 @@
...
+
+/**
+ * Automatically rotates an image based on EXIF Orientation.
+ */
+#[ImageEffect(
+  id: "farm_image_auto_orient",
+  label: new TranslatableMarkup("Auto-orient"),
+  description: new TranslatableMarkup("Automatically rotates an image based on EXIF Orientation.")
+)]
+class AutoOrientImageEffect extends ConfigurableImageEffectBase implements ContainerFactoryPluginInterface {
```
Comment (symbioquine) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Interesting, I hadn't seen this (new?) style of class documentation yet...

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 6]
```diff
@@ -0,0 +1,204 @@
...
+
+  /**
+   * {@inheritdoc}
+   */
+  public function applyEffect(ImageInterface $image) {
+
+    // Only proceed if the exif PHP extension is loaded.
+    if (!extension_loaded('exif')) {
+      return TRUE;
+    }
```
Comment (symbioquine) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php:73]: Should this check also occur at the top of `transformDimensions`? The [docs](https://api.drupal.org/api/drupal/core%21modules%21image%21src%21ConfigurableImageEffectBase.php/class/ConfigurableImageEffectBase/8.9.x) imply but don't really guarantee that it won't be called if no effect was applied here...

**Comment by mstenta** [comment]
Force pushed to fix `phpcs` and `phpstan` complaints. Thanks for the review @symbioquine! 'll dig into your feedback next.

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 5 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Yea! It's a new feature of PHP 8: https://www.php.net/manual/en/language.attributes.overview.php

We are in the process of migrating from Symfony's "annotations" to these new attributes: https://www.drupal.org/project/farm/issues/3461548

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 1 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Agreed! I also added a comment to `transformDimensions()` because that was also inspired by Image Effects code.

Commit: https://github.com/farmOS/farmOS/pull/941/commits/29cb9cac312364f35c0bef84c7b5799d289223de

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 6 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php:73]: Yes - good point. Fixup commit: https://github.com/farmOS/farmOS/pull/941/commits/2415dde6b049eb9e5c186876da8270bdfa00aef8

File: modules/core/image/farm_image.install (hunk 2 above)
Comment (mstenta) [reply modules/core/image/farm_image.install]: Good call - fixup commit: https://github.com/farmOS/farmOS/pull/941/commits/1ec09787d03eda62b5ab60ca2976c286d6b96187

File: modules/core/entity/farm_entity.post_update.php (hunk 3 above)
Comment (mstenta) [reply modules/core/entity/farm_entity.post_update.php]: Yes that's true. We got burned by that issue ourselves when a contrib module uninstalled a submodule we were depending on.

I'll look into checking whether or not other modules depend on `exif_orientation` before uninstalling it.

The catch is: since we're adding the `exif` PHP extension, if the `exif_orientation` module stays installed then it will start working (it wasn't because we didn't have `exif`). And that means that original images will start to get rotated, losing their EXIF data in the process. But if someone is depending on `exif_orientation`, then I suppose that's on them...

File: docker/Dockerfile (hunk 4 above)
Comment (mstenta) [reply docker/Dockerfile:34]: It is a soft dependency, but good idea to at least mention it in the server requirements docs. I added a commit: https://github.com/farmOS/farmOS/pull/941/commits/dac2375568da587d7812957ff343169d85ba867b

File: modules/core/entity/farm_entity.post_update.php (hunk 3 above)
Comment (mstenta) [reply modules/core/entity/farm_entity.post_update.php]: fixup: https://github.com/farmOS/farmOS/pull/941/commits/3d03f2d525bb722d0373ae249dc1d37d735ae8ad

**Review by symbioquine — APPROVED** [review]

**Comment by mstenta** [comment]
Thanks for the reviews and approval @symbioquine! I squashed the fixup commits, resolved your review conversations, and force pushed.

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 7]
```diff
@@ -0,0 +1,217 @@
...
+
+    // Only work with supported image types.
+    $mime_types = [
+      'image/jpeg',
+      'image/png',
+      'image/tiff',
+    ];
```
Comment (paul121) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Just noting that `tiff` isn't included in our `image` field file extensions: https://github.com/farmOS/farmOS/blob/b99e1ae519bf79c8e28ca76ab922d30a13d20427/modules/core/field/src/FarmFieldFactory.php#L631-L632

I read that `gif` doesn't include exif metadata so that's OK. Also wondering if we should add support for `webp` images, but could be a followup.

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 8]
```diff
@@ -0,0 +1,217 @@
...
+   * Load EXIF Orientation value from an image file.
+   *
+   * @param string $uri
+   *   The image file URI.
+   *
+   * @return int|null
+   *   Returns an integer representing the EXIF Orientation value, or NULL if no
+   *   Orientation key was found.
+   */
+  protected function loadExifOrientation($uri) {
```
Comment (paul121) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Can add some types here
```suggestion
  protected function loadExifOrientation(string $uri): ?int {
```

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 9]
```diff
@@ -0,0 +1,217 @@
...
+      return;
+    }
+
+    // This logic is adapted from the Drupal Image Effects module.
+    // @see https://git.drupalcode.org/project/image_effects/-/blob/730a1e6f5f947ef4d6eec5d359c6968ce93594f9/src/Plugin/ImageEffect/AutoOrientImageEffect.php
+    $dimensions['width'] = $dimensions['width'] ? (int) $dimensions['width'] : NULL;
+    $dimensions['height'] = $dimensions['height'] ? (int) $dimensions['height'] : NULL;
+    if ($dimensions['width'] && $dimensions['height']) {
+      $orientation = $this->loadExifOrientation($uri);
+      if (in_array($orientation, [5, 6, 7, 8])) {
```
Comment (paul121) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php:175]: Check that returned orientation value is not null

```suggestion
      $orientation = $this->loadExifOrientation($uri);
      if ($orientation && in_array($orientation, [5, 6, 7, 8])) {
```

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 10]
```diff
@@ -0,0 +1,217 @@
...
+    // Otherwise return NULL.
+    return NULL;
+  }
+
+  /**
+   * {@inheritdoc}
+   */
+  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
+    return $form;
+  }
```
Comment (paul121) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Since this effect doesn't use any configuration, could we extend directly from `ImageEffectBase`?

If we did have configuration I think we would need to define the `image.effect.farm_image_auto_orient` schema, but without configuration I think we're OK. I see the core `image_module_test` only provides a schema for the configurable image effect it provides, but the non configurable effects are not included: https://git.drupalcode.org/project/drupal/-/blob/10.5.x/core/modules/image/tests/modules/image_module_test/config/schema/image_module_test.schema.yml?ref_type=heads

File: modules/core/image/farm_image.install [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+ */
+function farm_image_install() {
+
+  // Add auto-orient effect to Drupal core image styles.
+  $styles = [
+    'large',
+    'medium',
+    'thumbnail',
+    'wide',
+  ];
```
Comment (paul121) [inline modules/core/image/farm_image.install:23]: I agree it makes sense to edit these BUT I'm also curious what the other option would look like, adding our own `farm_large`, etc image styles that we could more easily manage ourselves. I'm just not familiar with image styles.

If we did this, would we just update the image field formatters to use our specified `farm_*` image style(s)?

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php [hunk 12]
```diff
@@ -0,0 +1,217 @@
...
+use Psr\Log\LoggerInterface;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+
+/**
+ * Automatically rotates an image based on EXIF Orientation.
+ */
+#[ImageEffect(
+  id: "farm_image_auto_orient",
+  label: new TranslatableMarkup("Auto-orient"),
+  description: new TranslatableMarkup("Automatically rotates an image based on EXIF Orientation.")
```
Comment (paul121) [inline modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Very minor but these strings could use single quotes to be more consistent?

**Review by paul121 — CHANGES_REQUESTED** [review]
Just some small things to change but this plan LGTM!

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 7 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: That's true. I included `tiff` in the allowed mime types because TIFFs support EXIF data. But you're right, `webp` also supports EXIF, so it should be included in the allowed mime types too.

And both should be added to our allowed file extensions in image fields, IMO.

Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Added a commit to this PR: https://github.com/farmOS/farmOS/pull/941/commits/8dbb9a87c3690f5f2b4574dfcf8dec4c7d18bd60

> And both should be added to our allowed file extensions in image fields, IMO.

I will open a separate PR for this.

Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Ah! Actually we do allow TIFFs, but in the `file` field, not the `image` field. I wonder if there was a reason for that. :thinking: I'll follow up on that in the separate PR...

https://github.com/farmOS/farmOS/blob/b99e1ae519bf79c8e28ca76ab922d30a13d20427/modules/core/field/src/FarmFieldFactory.php#L626-L627

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 8 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Good call. Fixup: https://github.com/farmOS/farmOS/pull/941/commits/bb961e86611a5e003b5f0176380ecbf91a7f8256

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 9 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php:175]: I had that originally and PHPStorm highlighted it, saying:

> Condition is unnecessary because it is checked by 'in_array($orientation, [5, 6, 7, 8])' 

In other words: `NULL` is not in the array `[5, 6, 7, 8]`, so it will work as expected.

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 10 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Ah good point! Fixup: https://github.com/farmOS/farmOS/pull/941/commits/c105ca32137c7811653842d808c69b34821c4900

File: modules/core/image/farm_image.install (hunk 11 above)
Comment (mstenta) [reply modules/core/image/farm_image.install:23]: Yes, that's another option we could consider. The Drupal `image` module installs these styles by default - and there's no way of preventing it from adding them because they are `config/install/image.style.*.yml` files.

https://git.drupalcode.org/project/drupal/-/tree/10.4.x/core/modules/image/config/install?ref_type=heads

If we add our own, and leave the Drupal core ones untouched, then we'll have duplicates/unused styles, which feels messy to me. I would probably want to consider removing the Drupal core ones if we did that. But that has it's own considerations (more code in our `hook_install()` to delete them, is it a breaking change? etc).

Up until now we haven't needed to think about this. And in this particular instance, I think it's simpler and more elegant to just add our effect to the core styles.

I'm open to considering providing our own, but I think we should have a good reason for it.

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 12 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Ah good catch! Fixup: https://github.com/farmOS/farmOS/pull/941/commits/2e9c9788261390d3e58bfece0351d2c2455f4817

**Comment by mstenta** [comment]
Thanks for the review @paul121! I responded to all your feedback. Requesting re-review... :-)

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 7 above)
Comment (mstenta) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php]: Followup PR: https://github.com/farmOS/farmOS/pull/942

File: modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php (hunk 9 above)
Comment (paul121) [reply modules/core/image/src/Plugin/ImageEffect/AutoOrientImageEffect.php:175]: Oh, great!

File: modules/core/image/farm_image.install (hunk 11 above)
Comment (paul121) [reply modules/core/image/farm_image.install:23]: I agree, if we get into any more complex image styles then we could consider it. Sounds good.

**Review by paul121 — APPROVED** [review]

**Comment by mstenta** [comment]
Thanks @paul121! Squashed fixups and resolved conversations. Force pushed for final tests to run before merging...
